### ISSUE TITLE
Error when exporting an MMD model from Blender

### ISSUE THREAD

**Issue by TheTruelycon** [sugiany/blender_mmd_tools#58]
An Error occurs when attempting to export model in MMD format from blender.

Traceback (most recent call last): File "D:\Program Files\Blender\2.78\scripts\addons\mmdtools\operators\fileio.py", line 203, in execute copy_textures=self.copy_textures, File "D:\Program Files\Blender\2.78\scripts\addons\mmd_tools\core\pmx\exporter.py", line 754, in export exporter.execute(filepath, **kwargs) File "D:\Program Files\Blender\2.78\scripts\addons\mmd_tools\core\pmx\exporter.py", line 734, in execute mesh_data.append(self._loadMeshData(i)) File "D:\Program Files\Blender\2.78\scripts\addons\mmd_tools\core\pmx\exporter.py", line 645, in __loadMeshData for i in meshObj.data.shape_keys.key_blocks: AttributeError: 'NoneType' object has no attribute 'key_blocks'
location: <unknown location>:-1

**Comment by powroupi** [comment]
Hello @TheTruelycon , Simply add a shape key to the mesh object will solve it. :smile:

**Comment by Hogarth-MMD** [comment]
@powroupi is the current developer of mmd_tools.
You can find lots of great bug fixes and additional features in the version of mmd_tools by @powroupi:
https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip
https://github.com/powroupi/blender_mmd_tools
https://github.com/powroupi/blender_mmd_tools/issues
