### ISSUE TITLE
RuntimeError: Operator bpy.ops.mmd_tools.import_vmd.poll() failed, context is incorrect

### ISSUE THREAD

**Issue by gs201510** [sugiany/blender_mmd_tools#79]
I'm trying to run blender4.2 with mmd_tool via --background in cli.
```python
bpy.ops.mmd_tools.import_vmd(filepath=animation_path)
```
this code throw error
```text
Traceback (most recent call last):
  File "/Users/gs/PycharmProjects/blender-builder/render_video.py", line 77, in <module>
    main()
  File "/Users/gs/PycharmProjects/blender-builder/render_video.py", line 68, in main
    import_vmd(animation_path)
  File "/Users/gs/PycharmProjects/blender-builder/render_video.py", line 23, in import_vmd
    bpy.ops.mmd_tools.import_vmd(filepath=animation_path)
  File "/Applications/Blender.app/Contents/Resources/4.2/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Operator bpy.ops.mmd_tools.import_vmd.poll() failed, context is incorrect
```

how to fix it? thanks

**Comment by ulyssas** [comment]
Install MMD Tools 4.x from Blender Preferences. Do not create issues on this repository.

This is where you make new issues. https://github.com/MMD-Blender/blender_mmd_tools/issues

<img width="772" height="660" alt="Image" src="https://github.com/user-attachments/assets/067c4a80-07f9-40fc-90ff-4071effe6300" />
